baseurl = "https://tonini.dev"
languagecode = "en-US"
theme = "researcher"
title = "Francesco Tonini"
enableEmoji = true
math = false
disableKinds = ["taxonomy", "term"]

googleAnalytics = "UA-84358665-4"

[params]
  author = "Francesco Tonini"
  description = "ELLIS Ph.D. candidate in Artificial Intelligence @ University of Trento."
  since = 1997
  [params.footer]
    text = "I'm not superstitious, but I'm a little 'stitious"
    url = "https://www.youtube.com/watch?v=39uoolmtjSA"
  [params.style]
    colorRed = "#007f5f"

  [[params.socialIcons]]
      name = "Github"
      icon = "fab fa-github"
      weight = 1
      url = "https://github.com/francescotonini/"
  [[params.socialIcons]]
    icon = "ai ai-google-scholar"
    title = "Scholar"
    url = "https://scholar.google.com/citations?user=tRTTFOwAAAAJ"
  [[params.socialIcons]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/toninifrancesco/"
  [[params.socialIcons]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/toninifrancesco/"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
